import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        {/*
          Runtime public config. Generated by docker-entrypoint.sh at container
          start from the environment, so a single prebuilt image can be
          reconfigured per deployment. Loaded before the app bundle so
          window.__ENV is set before any client code reads it. A committed
          placeholder keeps local `next dev` working (it falls back to
          build-time process.env).
        */}
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="/__env.js" />
      </Head>
      <body className="antialiased">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
